apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: test:v1
      env:
        - name: ENTRYPOINT_PATH
          value: "/home/test/start-dev.sh"
        - name: TEST_ENV
          value: "dynamic param"
