apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-service-account-rolebinding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: default  # 默认的 serviceaccount
    namespace: argo
roleRef:
  kind: Role
  name: argo-service-account-role
  apiGroup: rbac.authorization.k8s.io
