apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo  # 将 Role 绑定到 argo 命名空间
  name: argo-service-account-role
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
