#阶段1
FROM golang:1.16 as builder
WORKDIR /go/src
# 复制源码并编译
COPY app.go ./
RUN go build  -o myapp app.go
#第二阶段：仅包含运行时环境
FROM scratch
WORKDIR /server
# 从构建阶段复制编译好的可执行文件
COPY --from=builder /go/src/myapp ./
# 指定启动命令
CMD ["./myapp"]
